import 'dotenv/config';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFile } from 'node:fs/promises';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import authRoutes from './routes/auth.js';
import profileRoutes from './routes/profile.js';
import socialRoutes from './routes/social.js';
import contentRoutes from './routes/content.js';
import schedulerRoutes from './routes/scheduler.js';
import analyticsRoutes from './routes/analytics.js';
import aiRoutes from './routes/ai.js';
import billingRoutes from './routes/billing.js';
import publisherRoutes from './routes/publisher.js';
import adminRoutes from './routes/admin.js';
import webhookRoutes from './routes/webhooks.js';
import { apiOk, apiError } from './utils/response.js';
const __filename=fileURLToPath(import.meta.url); const __dirname=path.dirname(__filename); const publicDir=path.join(__dirname,'public');
const SUPABASE_URL=process.env.SUPABASE_URL||'https://ofisyujlpvnuxwiquafm.supabase.co'; const SUPABASE_ANON_KEY=process.env.SUPABASE_ANON_KEY||'sb_publishable_24biTaIviWxGdoS4uzO1YA_KvxWxsaw';
const app=express(); const port=Number(process.env.PORT||3000); const origin=process.env.APP_ORIGIN||undefined;
app.set('trust proxy',1); app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:{policy:'cross-origin'}})); app.use(cors({origin:origin||true,credentials:false,methods:['GET','POST','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','X-Youtube-Upload-Url','Content-Range','X-Upload-Content-Type']})); app.use(morgan(process.env.NODE_ENV==='production'?'combined':'dev')); app.use('/api/webhooks',express.raw({type:'application/json',limit:'1mb'})); app.use(express.json({limit:'1mb'})); app.use('/api/',rateLimit({windowMs:60000,limit:120,standardHeaders:true,legacyHeaders:false}));
app.get('/api/health',(_req,res)=>res.json(apiOk({service:'grovia',status:'ok',time:new Date().toISOString()}))); app.get('/api/public-config',(_req,res)=>res.json(apiOk({supabaseUrl:SUPABASE_URL,supabaseAnonKey:SUPABASE_ANON_KEY})));
app.use('/api/auth',authRoutes); app.use('/api/profile',profileRoutes); app.use('/api/social',socialRoutes); app.use('/api/content',contentRoutes); app.use('/api/scheduler',schedulerRoutes); app.use('/api/analytics',analyticsRoutes); app.use('/api/ai',aiRoutes); app.use('/api/billing',billingRoutes); app.use('/api/publisher',publisherRoutes); app.use('/api/admin',adminRoutes); app.use('/api/webhooks',webhookRoutes);
app.use('/login',express.static(path.join(publicDir,'login'),{extensions:['html']}));
app.get(['/user','/user/'],async(_req,res,next)=>{try{const file=await readFile(path.join(publicDir,'user','index.html'),'utf8');const injected='\n<script src="/user/api-stability.js?v=20260830-2"></script>\n<script src="/user/overview-recovery.js"></script>\n<script src="/user/youtube-connect.js"></script>\n<script src="/user/growth-id-fix.js?v=20260830-2"></script>\n<script src="/user/user-enhance.js"></script>\n<script src="/user/growth-layout-fix.js?v=20260830-2"></script>\n<script src="/user/analytics-ui.js"></script>\n<script src="/user/ai-content.js"></script>\n<script src="/user/content-editor.js"></script>\n<script src="/user/scheduler-ui.js"></script>\n<script src="/user/publisher-ui-v2.js?v=20260830-3"></script>\n<script src="/user/growth-engine.js?v=20260830-3"></script>\n<script src="/user/growth-plan.js?v=20260830-2"></script>\n<script src="/user/page-modules.js?v=20260830-2"></script>\n';res.type('html').send(file.replace('</body>',injected+'</body>'));}catch(e){next(e)}});
app.use('/user',express.static(path.join(publicDir,'user'),{extensions:['html']}));
app.get('/admin',async(_req,res,next)=>{try{const file=await readFile(path.join(publicDir,'admin','index.html'),'utf8');const injected='\n<script src="/admin/admin-enhance.js"></script>\n';res.type('html').send(file.replace('</body>',injected+'</body>'));}catch(e){next(e)}}); app.use('/admin',express.static(path.join(publicDir,'admin'),{extensions:['html']}));
app.get('/',(_req,res)=>res.sendFile(path.join(publicDir,'login','index.html'))); app.use((req,res)=>res.status(404).json(apiError('NOT_FOUND',`Route tidak ditemukan: ${req.method} ${req.path}`))); app.use((err,_req,res,_next)=>{console.error('Unhandled error',err);res.status(500).json(apiError('INTERNAL_ERROR',err?.message||'Terjadi kesalahan internal.'));});
if(process.env.NODE_ENV!=='production'&&process.env.NODE_ENV!=='test')app.listen(port,()=>console.log(`GROVIA server listening on ${port}`)); export default app;
