-- Use the same additive GROVIA USER V2 production schema already approved/run in Supabase.
-- This file is intentionally a migration reference; do not run destructive resets.
create extension if not exists pgcrypto;
create table if not exists public.grovia_profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_url text, timezone text not null default 'Asia/Jakarta', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.grovia_social_accounts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, platform text not null, handle text, followers bigint not null default 0, engagement_rate numeric(8,3) not null default 0, status text not null default 'connected', token_expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.grovia_content_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, format text, status text not null default 'draft', platforms text[] not null default '{}', body jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), published_at timestamptz);
create table if not exists public.grovia_scheduled_posts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, content_id uuid references public.grovia_content_items(id) on delete set null, platform text not null, scheduled_at timestamptz not null, status text not null default 'scheduled', created_at timestamptz not null default now());
create table if not exists public.grovia_analytics_daily (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, metric_date date not null, followers bigint not null default 0, reach bigint not null default 0, views bigint not null default 0, watch_time_minutes numeric(14,2) not null default 0, engagement_rate numeric(8,3) not null default 0, created_at timestamptz not null default now(), unique(user_id, metric_date));
create table if not exists public.grovia_subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, plan text not null, status text not null default 'active', monthly_price numeric(14,2) not null default 0, period_end timestamptz, created_at timestamptz not null default now());
create table if not exists public.grovia_ai_usage (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, credits_used integer not null default 0 check (credits_used >= 0), feature text, created_at timestamptz not null default now());
